variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_STRATEGY: "fetch"
  GIT_CHECKOUT: "true"
  GIT_SSL_NO_VERIFY: "1"
  ENGINE_VERSION: "dev-dc-epic-5-2-1"

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - static-analysis

default:
  interruptible: true

pre-commit:
  image: python:3.11
  stage: static-analysis
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
    GIT_LFS_SKIP_SMUDGE: "1"
    # Soft lock is checked in a different job
    SKIP: check_locks
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train" && $CI_COMMIT_MESSAGE !~ /^Add changelog for version .*/
      # Verify on main without blocking subsequent jobs
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE !~ /^Add changelog for version .*/
      allow_failure: true
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - pip install pre-commit
  script:
    - pre-commit run --verbose --show-diff-on-failure --all-files --color always
  retry: 1
  # Select runner
  tags:
    - linux
    - docker
    - t0

flawfinder-sast:
  stage: static-analysis
  variables:
    SAST_FLAWFINDER_LEVEL: 1
    SAST_EXCLUDED_PATHS: Dreamcatcher/Plugins
    SEARCH_MAX_DEPTH: 10
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train"
